language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build --config _config.yml,_config_gh_pages.yml
after_success:
- echo "Pull request number - ${TRAVIS_PULL_REQUEST}"
- echo "Target branch name - ${TRAVIS_BRANCH}"
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'source' ]; then
  chmod +x ./scripts/deploy;
  source scripts/deploy;
  fi;
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO=github.com/Vinatorul/vinatorul.github.io.git
  - REPO_TARGET_BRANCH=master
sudo: false
